# Generated by Django 4.2.7 on 2023-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Descuentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('categoria_interes', models.CharField(max_length=100)),
            ],
        ),
    ]
