# Generated by Django 4.2.7 on 2023-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Descuentos', '0004_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
