# Generated by Django 4.2.7 on 2023-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Descuentos', '0005_producto_imagen_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
